# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'



variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300' # replace this value with the version that you need for your project

- script: dotnet test test/Spreads.LMDB.Tests/Spreads.LMDB.Tests.csproj -c Release -v m
  displayName: 'Test Release'
- script: dotnet test test/Spreads.LMDB.Tests/Spreads.LMDB.Tests.csproj -c Debug -v m
  displayName: 'Test Debug'